# Generated by Django 2.2.10 on 2020-02-26 21:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance_ID', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('part_number_affected', models.CharField(max_length=200)),
                ('tool_serial_number_affected', models.CharField(blank=True, max_length=200, null=True)),
                ('project_description', models.TextField(max_length=400)),
                ('project_justification', models.TextField(max_length=400)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField()),
                ('constraint_end_date', models.DateField(blank=True, null=True)),
                ('design_job', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('commodity', models.CharField(choices=[('Machining', 'Machining'), ('Composites and Fabrications', 'Composites and Fabrications'), ('Structural Castings', 'Structural Castings'), ('Blades', 'Blades'), ('Vanes and Rings', 'Vanes and Rings')], max_length=50)),
                ('complexity', models.CharField(choices=[('Regular', 'Regular'), ('Complex', 'Complex')], default='Regular', max_length=10)),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], default='Queued', max_length=10)),
            ],
            options={
                'permissions': (('can_view_project', 'Can view project'),),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.IntegerField(unique=True)),
                ('vendor_name', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('USA', 'USA'), ('CANADA', 'CANADA'), ('OTHER', 'OTHER')], default='CANADA', max_length=10)),
            ],
            options={
                'ordering': ['vendor_name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(max_length=200)),
                ('comment', models.TextField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('is_completed', models.BooleanField()),
                ('project_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('entry_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('project_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'ordering': ['-entry_date', '-due_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('Form 10024', 'Form 10024'), ('Form 10141', 'Form 10141'), ('Form 11212', 'Form 11212'), ('Form 11248', 'Form 1248'), ('Form 11615', 'Form 11615'), ('Form 11674', 'Form 11674'), ('Form 12165', 'Form 12165'), ('Invoice', 'Invoice'), ('Business Case', 'Business Case'), ('Quote', 'Quote'), ('Contract', 'Contract'), ('Other', 'Other')], default='Other', max_length=20)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('amount', models.FloatField(max_length=20)),
                ('currency', models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD'), ('OTHER', 'Other')], default='USD', max_length=5)),
                ('expense_type', models.CharField(choices=[('CAPEX', 'CAPEX'), ('OPEX', 'OPEX')], default='CAPEX', max_length=5)),
                ('entry_date', models.DateField(default=datetime.date.today)),
                ('project_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Supplier'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
