# Generated by Django 2.2.10 on 2020-02-27 01:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('viewflow', '0008_jsonfield_and_artifact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=200)),
                ('revision', models.CharField(default='-', max_length=3)),
                ('part_description', models.TextField(max_length=400)),
                ('status', models.CharField(choices=[('In Development', 'In Development'), ('Released', 'Released'), ('Obsolete', 'Obsolete')], default='In Development', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('tool_serial_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tool_cavitiy_numbers', models.CharField(blank=True, max_length=10, null=True)),
                ('tool_description', models.TextField(max_length=400)),
                ('year_built', models.IntegerField()),
                ('is_audit_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Development', 'Development'), ('Production', 'Production'), ('Stored', 'Stored')], default='Development', max_length=20)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Supplier')),
                ('part_produced', models.ManyToManyField(to='tooling.Part')),
            ],
        ),
        migrations.CreateModel(
            name='ToolCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_condition', models.CharField(choices=[('New', 'New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Wear-Out', 'Wear-Out')], default='New', max_length=10)),
                ('life', models.IntegerField()),
                ('life_remaining', models.IntegerField()),
                ('tool_yield', models.FloatField(default=0.95)),
                ('parts_forecasted', models.IntegerField()),
                ('months_forecasted', models.IntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('date_assessment', models.DateField(default=datetime.date.today)),
                ('risk', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=8)),
                ('tool_inspected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tooling.Tool')),
            ],
        ),
        migrations.CreateModel(
            name='ToolConditionProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(null=True)),
                ('audit_status', models.CharField(choices=[('SCF', 'Successful'), ('ERR', 'Unsuccessful')], default=None, max_length=3, null=True)),
                ('tool_condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tooling.ToolCondition')),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
    ]
