# Generated by Django 2.2.10 on 2020-02-27 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tooling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolconditionprocess',
            name='tool_condition',
        ),
        migrations.AddField(
            model_name='toolconditionprocess',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tooling.Tool'),
        ),
    ]
