# Generated by Django 2.2.10 on 2020-02-27 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_supplier_account_manager'),
        ('tooling', '0004_auto_20200227_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolconditionprocess',
            name='tool_inspected',
        ),
        migrations.AddField(
            model_name='toolconditionprocess',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Supplier'),
        ),
    ]
